import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { ballsToOvers, calcSR, calcEconomy, getResult, bowlerBalls, chasingMaxWickets, tossSummary } from './calculations'

const NAVY = [17, 24, 39]

/** Batting rows for one innings' batsmanStats map (name + dismissal, R, B, 4s, 6s, SR). */
function battingRows(stats) {
  return Object.entries(stats || {})
    .filter(([, v]) => v.balls > 0 || v.runs > 0)
    .map(([name, s]) => [
      s.out && s.dismissal ? `${name}\n${s.dismissal}` : `${name}\nnot out`,
      s.runs, s.balls, s.fours, s.sixes, calcSR(s.runs, s.balls),
    ])
}

/** Bowling rows for one innings' bowlerStats map (name, O, R, W, ECO). */
function bowlingRows(stats) {
  return Object.entries(stats || {})
    .filter(([, v]) => v.balls > 0 || v.overs > 0)
    .map(([name, s]) => {
      const tb = bowlerBalls(s)
      return [name, ballsToOvers(tb), s.runs, s.wickets, calcEconomy(s.runs, tb)]
    })
}

export function downloadPDF(match) {
  if (!match) return

  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const margin = 40
  let y = 50

  // ── Header ────────────────────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.setTextColor(20)
  doc.text(match.matchName || 'Match Scorecard', margin, y)
  y += 18

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(110)
  const meta = [
    `Date: ${new Date(match.date).toLocaleString()}`,
    `Overs: ${match.totalOvers}`,
    match.powerplayOvers ? `Powerplay: ${match.powerplayOvers} ov` : null,
  ].filter(Boolean).join('    ')
  doc.text(meta, margin, y)
  y += 18

  // ── Result ────────────────────────────────────────────────────────────────
  const inn1 = match.innings1
  const inn2 = match.innings2
  if (inn1 && inn2) {
    const res = getResult({ ...inn1 }, { ...inn2 }, chasingMaxWickets(match))
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(20)
    doc.text(`Result: ${res}`, margin, y)
  }

  // ── Toss ──────────────────────────────────────────────────────────────────
  // History entries carry the toss fields; older entries saved before the toss
  // feature won't, and tossSummary returns '' for those.
  const toss = tossSummary(match)
  if (toss) {
    y += 14
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(110)
    doc.text(toss, margin, y)
  }

  const battingHead = [['Batter', 'R', 'B', '4s', '6s', 'SR']]
  const bowlingHead = [['Bowler', 'O', 'R', 'W', 'ECO']]

  const drawTable = (head, body) => {
    const cols = head[0].length
    const rows = body.length ? body : [Array.from({ length: cols }, (_, i) => (i === 0 ? '—' : ''))]
    autoTable(doc, {
      head,
      body: rows,
      startY: y + 8,
      margin: { left: margin, right: margin },
      theme: 'grid',
      styles: { font: 'helvetica', fontSize: 9, cellPadding: 4, valign: 'middle', textColor: 30, lineColor: [220, 220, 220] },
      headStyles: { fillColor: NAVY, textColor: 255, fontStyle: 'bold', halign: 'center' },
      bodyStyles: { halign: 'center' },
      columnStyles: { 0: { halign: 'left', cellWidth: 'auto' } },
    })
    y = doc.lastAutoTable.finalY
  }

  const drawSection = (title) => {
    y += 24
    const pageHeight = doc.internal.pageSize.getHeight()
    if (y > pageHeight - 90) { doc.addPage(); y = 50 }
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(20)
    doc.text(title, margin, y)
  }

  if (inn1) {
    drawSection(`${inn1.teamName} — 1st Innings   ${inn1.score}/${inn1.wickets}  (${ballsToOvers(inn1.balls)} ov)`)
    drawTable(battingHead, battingRows(inn1.batsmanStats))
    drawTable(bowlingHead, bowlingRows(inn1.bowlerStats))
  }
  if (inn2) {
    drawSection(`${inn2.teamName} — 2nd Innings   ${inn2.score}/${inn2.wickets}  (${ballsToOvers(inn2.balls)} ov)`)
    drawTable(battingHead, battingRows(inn2.batsmanStats))
    drawTable(bowlingHead, bowlingRows(inn2.bowlerStats))
  }

  // ── Footer ────────────────────────────────────────────────────────────────
  y = (doc.lastAutoTable?.finalY || y) + 26
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(140)
  doc.text('Generated by CricHub.in', margin, y)

  const safeName = (match.matchName || 'scorecard').replace(/[^a-z0-9]/gi, '_')
  doc.save(`${safeName}_scorecard.pdf`)
}
