import { ballsToOvers, calcSR, calcEconomy, getResult } from './calculations'

export function downloadPDF(match) {
  if (!match) return

  const lines = []
  const add = (s) => lines.push(s)
  const hr = () => add('─'.repeat(52))

  add(`MATCH SCORECARD — ${match.matchName}`)
  add(`Date: ${new Date(match.date).toLocaleString()}`)
  add(`Overs: ${match.totalOvers}`)
  if (match.powerplayOvers) add(`Powerplay: ${match.powerplayOvers} overs`)
  hr()

  // Result
  const inn1 = match.innings1
  const inn2 = match.innings2
  if (inn1 && inn2) {
    const res = getResult(
      { ...inn1, teamName: inn1.teamName },
      { ...inn2 },
      match.totalOvers
    )
    add(`RESULT: ${res}`)
  }
  hr()

  // Inn 1
  if (inn1) {
    add(`\n${inn1.teamName} — 1st Innings: ${inn1.score}/${inn1.wickets} (${ballsToOvers(inn1.balls)} ov)`)
    hr()
    add(`${'NAME'.padEnd(18)}${'R'.padStart(5)}${'B'.padStart(5)}${'4s'.padStart(5)}${'6s'.padStart(5)}${'SR'.padStart(8)}`)
    Object.entries(inn1.batsmanStats || {}).filter(([, v]) => v.balls > 0 || v.runs > 0).forEach(([name, s]) => {
      add(`${name.padEnd(18)}${String(s.runs).padStart(5)}${String(s.balls).padStart(5)}${String(s.fours).padStart(5)}${String(s.sixes).padStart(5)}${calcSR(s.runs, s.balls).padStart(8)}`)
      if (s.out && s.dismissal) add(`  ${s.dismissal}`)
    })
    hr()
    add(`${'BOWLER'.padEnd(18)}${'O'.padStart(5)}${'R'.padStart(5)}${'W'.padStart(5)}${'ECO'.padStart(8)}`)
    Object.entries(inn1.bowlerStats || {}).filter(([, v]) => v.balls > 0 || v.overs > 0).forEach(([name, s]) => {
      const tb = (s.overs || 0) * 6 + (s.balls || 0)
      add(`${name.padEnd(18)}${ballsToOvers(tb).padStart(5)}${String(s.runs).padStart(5)}${String(s.wickets).padStart(5)}${calcEconomy(s.runs, tb).padStart(8)}`)
    })
  }

  // Inn 2
  if (inn2) {
    add(`\n${inn2.teamName} — 2nd Innings: ${inn2.score}/${inn2.wickets} (${ballsToOvers(inn2.balls)} ov)`)
    hr()
    add(`${'NAME'.padEnd(18)}${'R'.padStart(5)}${'B'.padStart(5)}${'4s'.padStart(5)}${'6s'.padStart(5)}${'SR'.padStart(8)}`)
    Object.entries(inn2.batsmanStats || {}).filter(([, v]) => v.balls > 0 || v.runs > 0).forEach(([name, s]) => {
      add(`${name.padEnd(18)}${String(s.runs).padStart(5)}${String(s.balls).padStart(5)}${String(s.fours).padStart(5)}${String(s.sixes).padStart(5)}${calcSR(s.runs, s.balls).padStart(8)}`)
      if (s.out && s.dismissal) add(`  ${s.dismissal}`)
    })
    hr()
    // Inn2 bowling stats
    if (inn2.bowlerStats) {
      add(`${'BOWLER'.padEnd(18)}${'O'.padStart(5)}${'R'.padStart(5)}${'W'.padStart(5)}${'ECO'.padStart(8)}`)
      Object.entries(inn2.bowlerStats).filter(([, v]) => v.balls > 0 || v.overs > 0).forEach(([name, s]) => {
        const tb = (s.overs || 0) * 6 + (s.balls || 0)
        add(`${name.padEnd(18)}${ballsToOvers(tb).padStart(5)}${String(s.runs).padStart(5)}${String(s.wickets).padStart(5)}${calcEconomy(s.runs, tb).padStart(8)}`)
      })
    }
  }
  hr()
  add('\nGenerated by CricHub.in')

  // Create text file download
  const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${match.matchName.replace(/[^a-z0-9]/gi, '_')}_scorecard.txt`
  a.click()
  URL.revokeObjectURL(url)
}
